apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-x
  namespace: default
spec:
  tokenSecret:
    name: doppler-token-x-clone
  project: x-clone
  config: prd
  managedSecret:
    name: x-backend-secret
    namespace: default
    type: Opaque
