apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: x
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: x
      images:
        - alias: frontend
          imageName: jeanmichelbb/twc-frontend
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^[0-9a-f]{40}$"
          manifestTargets:
            kustomize:
              name: jeanmichelbb/twc-frontend
        - alias: backend
          imageName: jeanmichelbb/twc-backend
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^[0-9a-f]{40}$"
          manifestTargets:
            kustomize:
              name: jeanmichelbb/twc-backend
      writeBackConfig:
        method: "git:secret:argocd/git-creds-github"
        gitConfig:
          branch: main
          writeBackTarget: "kustomization:."
