apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doppler-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - image-updater.yaml

images:
  - name: jeanmichelbb/twc-frontend
    newTag: d775dd0d718de47f1a43f30e7c4eaf4974a9b443
    newName: jeanmichelbb/twc-frontend
  - name: jeanmichelbb/twc-backend
    newTag: 93a89f10728706112e25242332c4f030ba1a007e
    newName: jeanmichelbb/twc-backend
