apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doppler-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - image-updater.yaml

images:
  - name: jeanmichelbb/twc-frontend
    newTag: 059bece9b06ae6b6c5838a178a90de2471f014c6
    newName: jeanmichelbb/twc-frontend
  - name: jeanmichelbb/twc-backend
    newTag: 93a89f10728706112e25242332c4f030ba1a007e
    newName: jeanmichelbb/twc-backend
