apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - doppler-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - image-updater.yaml
  - networkpolicy.yaml

images:
  - name: jeanmichelbb/twc-frontend
    newTag: a65b12575aa886f3f5bbc764583e1f8cfb19f7df
    newName: jeanmichelbb/twc-frontend
  - name: jeanmichelbb/twc-backend
    newTag: d775dd0d718de47f1a43f30e7c4eaf4974a9b443
    newName: jeanmichelbb/twc-backend
